[build]
builder = "nixpacks"

[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "ffmpeg",
  "libffi",
  "libnss3",
  "libx11",
  "libxcomposite",
  "libxcursor",
  "libxdamage",
  "libxext",
  "libxfixes",
  "libxi",
  "libxtst",
  "libxrandr",
  "gtk3",
  "pango",
  "atk",
  "cups"
]

[phases.install]
cmd = "pip3 install --upgrade pip && pip3 install -r requirements.txt"

[phases.start]
cmd = "python3 espaluz_bridge.py"

