[build]
builder = "nixpacks"

providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "ffmpeg",
  "tesseract",
  "libffi",
  "gtk3",
  "pango",
  "atk",
  "cups"
]

[phases.install]
cmd = "pip install --upgrade pip && pip install -r requirements.txt"

[phases.start]
cmd = "python espaluz_bridge.py"
